# Generated by Django 4.0.4 on 2022-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcaruser',
            name='user_car',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
