# Generated by Django 4.0.4 on 2022-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customcaruser_user_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcaruser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customcaruser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
