# Generated by Django 4.0.4 on 2022-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_customcaruser_deleted_at_customcaruser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcaruser',
            name='CREATE_ON',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcaruser',
            name='UPDATE_ON',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
