# Generated by Django 4.0.4 on 2022-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_rename_create_on_customcaruser_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcaruser',
            old_name='user_car',
            new_name='hometown',
        ),
        migrations.AddField(
            model_name='customcaruser',
            name='data_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customcaruser',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
