# Generated by Django 4.0.4 on 2022-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rest', '0003_remove_deletedat_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
