# Generated by Django 4.0.4 on 2022-05-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rest', '0003_carmodel_usercar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='CREATE_ON',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carbrand',
            old_name='UPDATE_ON',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='CREATE_ON',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='UPDATE_ON',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='usercar',
            old_name='CREATE_ON',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usercar',
            old_name='UPDATE_ON',
            new_name='updated_at',
        ),
    ]
