# Generated by Django 4.0.4 on 2022-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rest', '0008_alter_carbrand_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
